title: Portrai
description: Portrai Landing Page 
sitename: PortrAI
baseurl: 
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME